In [ ]:
ndarray basic

In [1]:
import numpy as np

In [19]:
#np.array?

In [20]:
# 1차원 배열 만들기
arr_1d = np.array([1, 2, 3, 4])
arr_1d

array([1, 2, 3, 4])

In [25]:
print('shape:', arr_1d.shape )
print('ndim:', arr_1d.ndim)

shape: (4,)
ndim: 1


In [10]:
arr_2d = np.array([[1, 2], [3, 4]])
arr_2d

array([[1, 2],
       [3, 4]])

In [ ]:
# 칼럼이름 없는 테이블(표)라고 생각하면 된다.
# 주의점 : 2차원은 대괄호가 2개 입니다.
#      1차원은 대괄호가 1개 입니다.  array([1, 2, 3, 4])

In [11]:
arr_2d.shape

(2, 2)

In [13]:
# 1열만 가져오자
arr_2d[:, 0:1]

array([[1],
       [3]])

In [14]:
# 2열만 가져오자
arr_2d[:, 1:2]

array([[2],
       [4]])

In [18]:
# 이렇게 추출한 애도 ?차원 배열일까요? 
# 2열만 가져와서 col2에 저장 후 출력해 보세요
# print('shape :', col2.??)
# print('차원 : ', col2.??)

col2 = arr_2d[:, 1:2]
print('shape :', col2.shape) #(2, 1)
print('차원 : ', col2.ndim)

shape : (2, 1)
차원 :  2


In [12]:
# 행추가
arr_2d_3행 = np.array([[1, 2], [3, 4], [5, 6]  ])
arr_2d_3행

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
print('shape :', arr_2d_3행.shape) 
print('차원 : ', arr_2d_3행.ndim)

shape : (3, 2)
차원 :  2


#### 1차원으로 뽑아내기
언제 자주 사용하는가?  
종속변수를 추출해서 담을때

In [28]:
# 1arr_2d_3행 > 1열을 1차원 array형태로 y에 담으세요. 
y = arr_2d_3행[:,1]
y

array([2, 4, 6])

In [30]:
print('shape :', y.shape) 
print('차원 : ', y.ndim)

shape : (3,)
차원 :  1


In [ ]:
# shape : (3,) 열이 없다

In [32]:
# 1arr_2d_3행 > 0번째 열을 1차원 array형태로 c1에 담으세요. 
c1 = arr_2d_3행[:,0]
c1

array([1, 3, 5])

In [33]:
print('shape :', c1.shape) 
print('차원 : ', c1.ndim)

shape : (3,)
차원 :  1


In [ ]:
Examples
--------
>>> np.array([1, 2, 3])
array([1, 2, 3])

Upcasting:

>>> np.array([1, 2, 3.0])
array([ 1.,  2.,  3.])

More than one dimension:

>>> np.array([[1, 2], [3, 4]])
array([[1, 2],
       [3, 4]])

Minimum dimensions 2:

>>> np.array([1, 2, 3], ndmin=2)
array([[1, 2, 3]])

Type provided:

>>> np.array([1, 2, 3], dtype=complex)
array([ 1.+0.j,  2.+0.j,  3.+0.j])

Data-type consisting of more than one element:

>>> x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
>>> x['a']
array([1, 3])

Creating an array from sub-classes:

>>> np.array(np.mat('1 2; 3 4'))
array([[1, 2],
       [3, 4]])

>>> np.array(np.mat('1 2; 3 4'), subok=True)
matrix([[1, 2],
        [3, 4]])